spring:
  mqtt:
    broker-url: tcp://broker.hivemq.com:1883
    client-id: airq-cloud-backend
    default-topic: airq/cloud/telemetry
  datasource:
    url: jdbc:postgresql://localhost:5432/airq
    username: postgres
    password: postgres

  # Brevo API configuration replacing SMTP to avoid port 587 blocking on cloud platforms
  brevo:
    api:
      url: https://api.brevo.com/v3/smtp/email
      key: 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
      sender: b01efb001@smtp-brevo.com

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
